segment.o: segment.c segment.h
	$(CC) $(CFLAGS) -c -o $@ $<

inode.o: inode.c inode.h
	$(CC) $(CFLAGS) -c -o $@ $<

lfs.o: lfs.c lfs.h
	$(CC) $(CFLAGS) -c -o $@ $<

cleaner.o: cleaner.c cleaner.h
	$(CC) $(CFLAGS) -c -o $@ $<
